name: containers

on:
  push:
    branches:
      - dev
      - v2
    paths:
      - packages/containers/**
      - .github/workflows/containers.yml
      - package.json
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ${{ vars.RUNNER_LINUX || 'ubuntu-24.04' }}
    timeout-minutes: 30
    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      TAG: "24.04"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup-devshell

      - uses: ./.github/actions/setup-docker

      - name: Build and push containers
        run: bun ./packages/containers/script/build.ts --push
        env:
          REGISTRY: ${{ env.REGISTRY }}
          TAG: ${{ env.TAG }}
