name: notify-discord

on:
  release:
    types: [released]

jobs:
  notify:
    runs-on: ${{ vars.RUNNER_LINUX || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check Discord webhook
        id: creds
        uses: ./.github/actions/check-secret
        with:
          secret: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send nicely-formatted embed to Discord
        if: steps.creds.outputs.available == 'true'
        uses: ./.github/actions/notify-discord
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
