name: publish-vscode

on:
  workflow_dispatch:
  push:
    tags:
      - "vscode-v*.*.*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  publish:
    runs-on: ${{ vars.RUNNER_LINUX || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Check VS Code credentials
        id: creds
        uses: ./.github/actions/check-secret
        with:
          secret: ${{ secrets.VSCE_PAT }}

      - uses: ./.github/actions/setup-devshell

      - run: git fetch --force --tags
      - run: bun install -g @vscode/vsce

      - name: Install extension dependencies
        run: bun install
        working-directory: ./sdks/vscode

      - name: Publish
        if: steps.creds.outputs.available == 'true'
        run: ./script/publish
        working-directory: ./sdks/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OPENVSX_TOKEN: ${{ secrets.OPENVSX_TOKEN }}
