name: release-github-action

on:
  push:
    branches:
      - dev
      - v2
    paths:
      - "github/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ vars.RUNNER_LINUX || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: ./.github/actions/setup-git-identity
        with:
          email: opencode@${{ github.repository_owner }}.dev

      - name: Release
        run: ./github/script/release
